### ISSUE TITLE
Error trying to run the demo Project

### ISSUE THREAD

**Issue by jojax** [benoitbryon/django-downloadview#92]
Problem  appears after running:
$ make runserver

demo syncdb --noinput
Traceback (most recent call last):
  File "/home/jojax/.virtualenvs/download_view/bin/demo", line 9, in <module>
    load_entry_point('django-downloadview-demo==1.7.dev0', 'console_scripts', 'demo')()
  File "/home/jojax/Projects/Test/django-downloadview/demo/demoproject/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 183, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.get_table_list(self.connection.cursor()):
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 165, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 122, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/jojax/.virtualenvs/download_view/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 374, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
Makefile:79: recipe for target 'demo' failed
make: *** [demo] Error 1

**Comment by benoitbryon** [comment]
Ah! We reported the same issues at the same time :)
#91 is a duplicate!

**Comment by benoitbryon** [comment]
From #91:

> Following demo's documentation, I get django.db.utils.OperationalError: unable to open database file error.
> Looks like the "var" folder is missing.
